# Generated by Django 4.2.6 on 2023-10-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("from_date", models.DateTimeField(auto_now_add=True)),
                ("to_date", models.DateTimeField()),
                ("is_finished", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("to_date", models.DateTimeField()),
                ("tags", models.CharField(max_length=255)),
                ("is_finished", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "finance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="home.finance"
                    ),
                ),
                ("notes", models.ManyToManyField(related_name="users", to="home.note")),
                (
                    "targets",
                    models.ManyToManyField(related_name="users", to="home.target"),
                ),
                ("tasks", models.ManyToManyField(related_name="users", to="home.task")),
            ],
        ),
        migrations.CreateModel(
            name="FinancePrediction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.financecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinanceOperation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_income", models.BooleanField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.financecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="finance",
            name="finance_operations",
            field=models.ManyToManyField(
                related_name="finance", to="home.financeoperation"
            ),
        ),
        migrations.AddField(
            model_name="finance",
            name="finance_predictions",
            field=models.ManyToManyField(
                related_name="finance", to="home.financeprediction"
            ),
        ),
    ]
